### ISSUE TITLE
tkn taskrun describe, doesn't show any sidecar info

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/cli#655]
# Expected Behavior

`tkn taskrun describe` would show sidecar info/basic status

# Actual Behavior

doesn't show any sidecars info

**Comment by vdemeester** [comment]
and done :wink:

**Comment by piyush-garg** [comment]
Fixed with #747 

/close

**Comment by danielhelfand** [comment]
This was only partially solved as #747 only shows names. We also need status.

**Comment by danielhelfand** [comment]
Leaving a note here that this will depend on the release of pipeline after `v0.10.1`.
